#!/usr/bin/env python3

import numpy as np
from mwr.util import readMrcNumpy
from mwr.util.generate import DataCubes
from mwr.simulation import TwoDPsf, TrDPsf
from mwr.simulation.simulate import apply_wedge
from mwr.models import unet
from scipy.ndimage.interpolation import rotate
import keras
from mwr.util.norm import normalize
from mwr.util.image import norm_save,toUint8,toUint16
from mwr.util.toTile import reform3D,DataWrapper
from tifffile import imsave
import mrcfile
from mwr.simulation.simulate import apply_wedge1
from mwr.util.image import *

def predict(model,weight,mrc,output,cubesize=64, cropsize=96, batchsize=8, gpuID='0', if_percentile=True):

    ngpus = len(gpuID.split(','))

    from keras.models import model_from_json
    json_file = open(model, 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    model = model_from_json(loaded_model_json)
    print(gpuID)
    if ngpus >1:
        from keras.utils import multi_gpu_model
        model = multi_gpu_model(model, gpus=ngpus, cpu_merge=True, cpu_relocation=False)
    model.load_weights(weight)

    print("Loaded model from disk")

    N = batchsize * ngpus

    if True:
        if True:
            root_name = mrc.split('/')[-1].split('.')[0]
            print('predicting:{}'.format(root_name))
            with mrcfile.open(mrc) as mrcData:
                real_data = mrcData.data.astype(np.float32)*-1
            real_data = normalize(real_data,percentile=if_percentile)
            data=np.expand_dims(real_data,axis=-1)
            reform_ins = reform3D(data)
            data = reform_ins.pad_and_crop_new(cubesize,cropsize)
            #to_predict_data_shape:(n,cropsize,cropsize,cropsize,1)
            #imposing wedge to every cubes
            #data=wedge_imposing(data)
            num_batches = data.shape[0]
            if num_batches%N == 0:
                append_number = 0
            else:
                append_number = N - num_batches%N
            data = np.append(data, data[0:append_number], axis = 0)

            outData=model.predict(data, batch_size= batchsize,verbose=1)

            outData = outData[0:num_batches]
            outData=reform_ins.restore_from_cubes_new(outData.reshape(outData.shape[0:-1]), cubesize, cropsize)

            outData = normalize(outData,percentile=if_percentile)
            with mrcfile.new(output, overwrite=True) as output_mrc:
                output_mrc.set_data(-outData)
    return 0

def wedge_imposing(data):
    #data are in 4 dimensions:(n,cropsize,cropsize,cropsize,1)
    dim = data.shape
    cubes=np.ones(dim)
    for i in range(dim[0]):
        print('**%d',i)
        one_cube=data[i,:,:,:,0]
        cubes[i,:,:,:,0]=apply_wedge1(one_cube)
    return cubes
    
def str2bool(v):
    if isinstance(v, bool):
       return v
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('mrc_file', type=str, default=None, help='Your mrc file')
    parser.add_argument('output_file', type=str, default=None, help='output mrc file')
    parser.add_argument('--weight', type=str, default='results/modellast.h5' ,help='Weight file name to save')
    parser.add_argument('--model', type=str, default='model.json' ,help='Data file name to save')
    parser.add_argument('--gpuID', type=str, default='0,1,2,3', help='number of gpu for training')
    parser.add_argument('--cubesize', type=int, default=64, help='size of cube')
    parser.add_argument('--cropsize', type=int, default=96, help='crop size larger than cube for overlapping tile')
    parser.add_argument('--batchsize', type=int, default=8, help='batch size')
    parser.add_argument('--norm', type=str, default='True', help='bool; default: percentile normlization')
    args = parser.parse_args()
    if_percentile = str2bool(args.norm)
    import os
    os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
    os.environ["CUDA_VISIBLE_DEVICES"]=args.gpuID 
    print('percentile:',if_percentile)
    predict(args.model,args.weight,args.mrc_file,args.output_file, cubesize=args.cubesize, cropsize=args.cropsize, batchsize=args.batchsize, gpuID=args.gpuID, if_percentile=if_percentile)
